'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { PROJECT_URL, renderSvg } = require('../src/svg');

const points = [
  { date: '2026-07-20', stars: 100, forks: 20, downloads: 1000 },
  { date: '2026-07-21', stars: 108, forks: 22, downloads: 1130 },
  { date: '2026-07-22', stars: 115, forks: 25, downloads: 1300 }
];

test('renders an accessible, adaptive, dependency-free SVG', () => {
  const svg = renderSvg({ repository: 'owner/repo', title: 'Growth & momentum', points, updatedAt: '2026-07-22T08:00:00Z' });
  assert.match(svg, /<title id="title">Growth &amp; momentum/);
  assert.match(svg, /prefers-color-scheme: dark/);
  assert.match(svg, /Release downloads/);
  assert.match(svg, /Generated by Repo Growth ↗/);
  assert.match(svg, new RegExp(`href="${PROJECT_URL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`));
  assert.doesNotMatch(svg, /(?:href|src)=["']https?:\/\/(?!github\.com\/MacRimi\/repo-growth)/);
});

test('renders a single point without invalid coordinates', () => {
  const svg = renderSvg({ repository: 'owner/repo', points: [points[0]], updatedAt: '2026-07-20T00:00:00Z' });
  assert.doesNotMatch(svg, /NaN|Infinity/);
});

test('renders only selected metrics and adapts the canvas height', () => {
  const two = renderSvg({ repository: 'owner/repo', points, metrics: ['stars', 'downloads'] });
  const one = renderSvg({ repository: 'owner/repo', points, metrics: ['forks'] });
  assert.match(two, /height="582"/);
  assert.match(two, />Stars</);
  assert.match(two, />Release downloads</);
  assert.doesNotMatch(two, />Forks</);
  assert.match(one, /height="444"/);
  assert.match(one, />Forks</);
  assert.doesNotMatch(one, />Stars</);
});

test('rejects unknown or empty metric selections', () => {
  assert.throws(() => renderSvg({ repository: 'owner/repo', points, metrics: [] }), /At least one metric/);
  assert.throws(() => renderSvg({ repository: 'owner/repo', points, metrics: ['views'] }), /Unknown metrics/);
});
