'use strict';

const METRICS = [
  { key: 'stars', label: 'Stars', color: '#8b5cf6', soft: '#c4b5fd' },
  { key: 'forks', label: 'Forks', color: '#06b6d4', soft: '#67e8f9' },
  { key: 'downloads', label: 'Release downloads', color: '#10b981', soft: '#6ee7b7' }
];
const PROJECT_URL = 'https://github.com/MacRimi/repo-growth';

function renderSvg({ repository, title = 'Project growth', points, updatedAt, metrics }) {
  if (!Array.isArray(points) || points.length === 0) {
    throw new Error('At least one history point is required to render the SVG.');
  }
  const selectedMetrics = resolveMetrics(metrics);
  const latest = points.at(-1);
  const first = points[0];
  const width = 1000;
  const surfaceHeight = 230 + selectedMetrics.length * 138;
  const height = surfaceHeight + 76;

  const cards = selectedMetrics.map((metric, index) => statCard(metric, latest, first, index, selectedMetrics.length)).join('');
  const charts = selectedMetrics.map((metric, index) => chartPanel(metric, points, index)).join('');
  const range = first.date === latest.date ? `Tracking since ${prettyDate(first.date)}` : `${prettyDate(first.date)} – ${prettyDate(latest.date)}`;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title desc">
  <title id="title">${escapeXml(title)} for ${escapeXml(repository)}</title>
  <desc id="desc">Repository growth dashboard showing ${escapeXml(selectedMetrics.map((metric) => metric.label.toLowerCase()).join(', '))} over time.</desc>
  <defs>
    <linearGradient id="background" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#fafafa"/><stop offset="1" stop-color="#f4f4f5"/>
    </linearGradient>
    ${selectedMetrics.map((metric) => `<linearGradient id="fill-${metric.key}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${metric.color}" stop-opacity=".24"/><stop offset="1" stop-color="${metric.color}" stop-opacity="0"/></linearGradient>`).join('')}
    <filter id="shadow" x="-10%" y="-10%" width="120%" height="130%"><feDropShadow dx="0" dy="8" stdDeviation="14" flood-color="#18181b" flood-opacity=".08"/></filter>
    <style>
      :root { color-scheme: light dark; }
      .bg { fill: url(#background); }
      .surface { fill: #ffffff; stroke: #e4e4e7; }
      .panel { fill: #ffffff; stroke: #e4e4e7; }
      .primary { fill: #18181b; }
      .secondary { fill: #71717a; }
      .grid { stroke: #e4e4e7; }
      text { font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
      @media (prefers-color-scheme: dark) {
        .bg { fill: #09090b; }
        .surface, .panel { fill: #111113; stroke: #27272a; }
        .primary { fill: #fafafa; }
        .secondary { fill: #a1a1aa; }
        .grid { stroke: #27272a; }
      }
    </style>
  </defs>
  <rect class="bg" width="1000" height="720" rx="28"/>
  <g transform="translate(42 38)">
    <rect x="0" y="0" width="916" height="${surfaceHeight}" rx="22" class="surface" filter="url(#shadow)"/>
    <text x="30" y="45" class="primary" font-size="26" font-weight="750" letter-spacing="-.5">${escapeXml(title)}</text>
    <text x="30" y="70" class="secondary" font-size="14">${escapeXml(repository)} · ${escapeXml(range)}</text>
    <g transform="translate(740 25)"><rect width="146" height="30" rx="15" fill="#8b5cf6" fill-opacity=".12"/><circle cx="17" cy="15" r="4" fill="#8b5cf6"/><text x="30" y="20" fill="#8b5cf6" font-size="11" font-weight="700" letter-spacing="1">LOCAL HISTORY</text></g>
    ${cards}
    ${charts}
    <text x="30" y="${surfaceHeight - 19}" class="secondary" font-size="11">Updated ${escapeXml(prettyTimestamp(updatedAt))}</text>
    <a href="${PROJECT_URL}" target="_blank" aria-label="Open the Repo Growth project">
      <text x="886" y="${surfaceHeight - 19}" fill="#8b5cf6" text-anchor="end" font-size="13" font-weight="700">Generated by Repo Growth ↗</text>
    </a>
  </g>
</svg>
`;
}

function statCard(metric, latest, first, index, count) {
  const gap = 20;
  const cardWidth = (856 - gap * (count - 1)) / count;
  const x = 30 + index * (cardWidth + gap);
  const value = Number(latest[metric.key]) || 0;
  const delta = value - (Number(first[metric.key]) || 0);
  const deltaText = delta === 0 ? 'No change yet' : `${delta > 0 ? '+' : '−'}${compact(Math.abs(delta))} tracked`;
  return `<g transform="translate(${x} 92)">
    <rect width="${cardWidth}" height="86" rx="16" class="panel"/>
    <rect x="16" y="17" width="6" height="52" rx="3" fill="${metric.color}"/>
    <text x="38" y="34" class="secondary" font-size="12" font-weight="650" letter-spacing=".3">${metric.label.toUpperCase()}</text>
    <text x="38" y="64" class="primary" font-size="27" font-weight="760" letter-spacing="-.5">${compact(value)}</text>
    <text x="${cardWidth - 26}" y="63" text-anchor="end" fill="${metric.color}" font-size="11" font-weight="650">${deltaText}</text>
  </g>`;
}

function chartPanel(metric, points, index) {
  const y = 197 + index * 138;
  const left = 220;
  const top = 19;
  const graphWidth = 650;
  const graphHeight = 86;
  const values = points.map((point) => Number(point[metric.key]) || 0);
  const minValue = Math.min(...values);
  const maxValue = Math.max(...values);
  const spread = Math.max(maxValue - minValue, 1);
  const pad = spread * 0.12;
  const low = Math.max(0, minValue - pad);
  const high = maxValue + pad;
  const coords = values.map((value, pointIndex) => {
    const x = left + (points.length === 1 ? graphWidth / 2 : pointIndex * graphWidth / (points.length - 1));
    const pointY = top + graphHeight - ((value - low) / Math.max(high - low, 1)) * graphHeight;
    return [round(x), round(pointY)];
  });
  const line = coords.map(([x, pointY], pointIndex) => `${pointIndex ? 'L' : 'M'}${x} ${pointY}`).join(' ');
  const area = `${line} L${coords.at(-1)[0]} ${top + graphHeight} L${coords[0][0]} ${top + graphHeight} Z`;
  const grid = [0, 0.5, 1].map((ratio) => `<line x1="${left}" x2="${left + graphWidth}" y1="${top + graphHeight * ratio}" y2="${top + graphHeight * ratio}" class="grid" stroke-width="1" stroke-dasharray="3 6"/>`).join('');

  return `<g transform="translate(30 ${y})">
    <rect width="856" height="122" rx="16" class="panel"/>
    <circle cx="20" cy="27" r="5" fill="${metric.color}"/>
    <text x="34" y="31" class="primary" font-size="14" font-weight="700">${metric.label}</text>
    <text x="20" y="62" class="primary" font-size="20" font-weight="750">${compact(values.at(-1))}</text>
    <text x="20" y="83" class="secondary" font-size="11">range ${compact(minValue)}–${compact(maxValue)}</text>
    ${grid}
    <path d="${area}" fill="url(#fill-${metric.key})"/>
    <path d="${line}" fill="none" stroke="${metric.color}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
    ${coords.map(([x, pointY], pointIndex) => pointIndex === coords.length - 1 ? `<circle cx="${x}" cy="${pointY}" r="5" fill="${metric.color}" stroke="#fff" stroke-width="2"/>` : '').join('')}
    <text x="${left}" y="116" class="secondary" font-size="10">${escapeXml(shortDate(points[0].date))}</text>
    <text x="${left + graphWidth}" y="116" text-anchor="end" class="secondary" font-size="10">${escapeXml(shortDate(points.at(-1).date))}</text>
  </g>`;
}

function compact(value) {
  return new Intl.NumberFormat('en', { notation: value >= 10000 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(value);
}

function prettyDate(date) {
  return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${date}T00:00:00Z`));
}

function shortDate(date) {
  return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', timeZone: 'UTC' }).format(new Date(`${date}T00:00:00Z`));
}

function prettyTimestamp(timestamp) {
  if (!timestamp) return 'just now';
  return new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeZone: 'UTC' }).format(new Date(timestamp));
}

function round(value) {
  return Math.round(value * 10) / 10;
}

function escapeXml(value) {
  return String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' })[character]);
}

function resolveMetrics(metrics) {
  const keys = metrics == null
    ? METRICS.map((metric) => metric.key)
    : (Array.isArray(metrics) ? metrics : String(metrics).split(',')).map((key) => key.trim().toLowerCase()).filter(Boolean);
  const uniqueKeys = [...new Set(keys)];
  if (uniqueKeys.length === 0) throw new Error('At least one metric must be selected.');
  const unknown = uniqueKeys.filter((key) => !METRICS.some((metric) => metric.key === key));
  if (unknown.length) throw new Error(`Unknown metrics: ${unknown.join(', ')}.`);
  return uniqueKeys.map((key) => METRICS.find((metric) => metric.key === key));
}

module.exports = { METRICS, PROJECT_URL, renderSvg, resolveMetrics, escapeXml };
